<?xml version="1.0" encoding="utf-8"?><?workdir /C:\SequoiaDB\doc\references\temp\references\exceptionmapping\topics?><?path2project ..\..\?><topic xmlns:ditaarch="http://dita.oasis-open.org/architecture/2005/" id="references_exception" ditaarch:DITAArchVersion="1.2" domains="(topic hi-d)                             (topic ut-d)                             (topic indexing-d)                            (topic hazard-d)                            (topic abbrev-d)                            (topic pr-d)                             (topic sw-d)                            (topic ui-d)    " class="- topic/topic " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="topic:1">
   <title class="- topic/title " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="title:1">Error Code List</title>
   <body class="- topic/body " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="body:1">
      <simpletable frame="all" relcolwidth="5.25* 1.0*" id="references_exceptionmapping_table" class="- topic/simpletable " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="simpletable:1">
         <sthead class="- topic/sthead " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="sthead:1">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:1">Description</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:2">Error Code</stentry>
         </sthead>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:1">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:3">IO Exception</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:4">-1</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:2">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:5">Out of Memory</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:6">-2</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:3">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:7">Permission Error</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:8">-3</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:4">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:9">File Not Exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:10">-4</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:5">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:11">File Exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:12">-5</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:6">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:13">Invalid Argument</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:14">-6</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:7">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:15">Invalid size</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:16">-7</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:8">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:17">Interrupt</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:18">-8</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:9">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:19">hit end of file</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:20">-9</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:10">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:21">system error</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:22">-10</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:11">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:23">has no space</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:24">-11</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:12">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:25">EDU status is not valid</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:26">-12</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:13">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:27">Timeout error</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:28">-13</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:14">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:29">Database is quiesced</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:30">-14</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:15">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:31">Network error</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:32">-15</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:16">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:33">Network is closed from remote</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:34">-16</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:17">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:35">Database is in shutdown status</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:36">-17</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:18">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:37">Application is forced</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:38">-18</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:19">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:39">Given path is not valid</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:40">-19</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:20">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:41">Unexpected file type specified</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:42">-20</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:21">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:43">There's no space for DMS</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:44">-21</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:22">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:45">collection already exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:46">-22</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:23">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:47">collection does not exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:48">-23</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:24">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:49">user record is too big</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:50">-24</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:25">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:51">record does not exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:52">-25</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:26">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:53">remote overflow record exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:54">-26</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:27">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:55">invalid record</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:56">-27</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:28">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:57">storage unit need reorg</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:58">-28</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:29">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:59">end of collection</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:60">-29</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:30">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:61">context is already opened</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:62">-30</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:31">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:63">context is closed</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:64">-31</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:32">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:65">option is not supported yet</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:66">-32</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:33">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:67">collection space already exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:68">-33</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:34">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:69">collection space not exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:70">-34</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:35">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:71">storage unit file is invalid</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:72">-35</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:36">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:73">context not exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:74">-36</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:37">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:75">more than one field has array</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:76">-37</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:38">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:77">duplicate key exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:78">-38</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:39">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:79">key is too large</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:80">-39</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:40">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:81">index extent has no space</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:82">-40</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:41">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:83">index key not exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:84">-41</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:42">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:85">hit max number of index</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:86">-42</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:43">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:87">failed to initialize index</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:88">-43</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:44">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:89">collection is dropped</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:90">-44</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:45">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:91">two records get same key and rid</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:92">-45</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:46">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:93">duplicate index name</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:94">-46</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:47">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:95">index name doesn't exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:96">-47</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:48">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:97">index flag is unexpected</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:98">-48</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:49">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:99">hit end of index</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:100">-49</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:50">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:101">hit max of dedup buffer</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:102">-50</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:51">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:103">invalid predicates</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:104">-51</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:52">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:105">index is no longer exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:106">-52</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:53">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:107">index hint is not valid</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:108">-53</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:54">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:109">no more temp tables avaliable</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:110">-54</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:55">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:111">exceed max number of SU</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:112">-55</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:56">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:113">$id index can't be dropped</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:114">-56</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:57">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:115">log was not found in log buf</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:116">-57</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:58">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:117">log was not found in log file</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:118">-58</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:59">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:119">replication group not exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:120">-59</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:60">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:121">replication group exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:122">-60</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:61">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:123">invalid request id is received</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:124">-61</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:62">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:125">session ID does not exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:126">-62</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:63">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:127">system edu can't be forced</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:128">-63</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:64">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:129">database is not connected</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:130">-64</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:65">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:131">unexpected result received</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:132">-65</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:66">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:133">corrupted record</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:134">-66</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:67">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:135">backup has already started</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:136">-67</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:68">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:137">backup not completed</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:138">-68</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:69">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:139">backup in progress mode</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:140">-69</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:70">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:141">backup file is damaged</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:142">-70</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:71">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:143">there's no primary found</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:144">-71</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:72">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:145">the requested node not exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:146">-72</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:73">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:147">help argument is specified</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:148">-73</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:74">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:149">connection state is not valid</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:150">-74</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:75">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:151">invalid handle</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:152">-75</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:76">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:153">client object is freed</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:154">-76</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:77">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:155">transfer has already listened</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:156">-77</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:78">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:157">can not listen specified addr</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:158">-78</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:79">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:159">cannot connect to specified addr</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:160">-79</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:80">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:161">connection does not exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:162">-80</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:81">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:163">failed to send</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:164">-81</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:82">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:165">timer id not found</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:166">-82</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:83">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:167">route info not found</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:168">-83</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:84">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:169">broken msg</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:170">-84</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:85">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:171">invalid net handle</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:172">-85</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:86">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:173">reorg file is not valid</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:174">-86</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:87">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:175">reorg file is in read only mode</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:176">-87</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:88">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:177">collection status is not valid</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:178">-88</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:89">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:179">collection is not in reorg state</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:180">-89</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:90">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:181">replication group is not activated</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:182">-90</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:91">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:183">the member is not in this group</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:184">-91</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:92">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:185">collection flag not compatible</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:186">-92</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:93">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:187">local group version is expired</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:188">-93</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:94">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:189">page size is not valid</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:190">-94</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:95">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:191">remote group version is expired</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:192">-95</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:96">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:193">failed to create a poll</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:194">-96</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:97">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:195">log record is corrupted</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:196">-97</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:98">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:197">given lsn greater than latest</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:198">-98</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:99">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:199">received unknown mesage</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:200">-99</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:100">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:201">updated information is same as old one</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:202">-100</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:101">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:203">unknow message</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:204">-101</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:102">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:205">empty heap</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:206">-102</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:103">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:207">not primary</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:208">-103</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:104">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:209">data node not enough</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:210">-104</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:105">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:211">data node have no catalog info</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:212">-105</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:106">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:213">data node catlog version old</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:214">-106</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:107">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:215">coord node catalog version old</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:216">-107</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:108">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:217">exceds the max group size</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:218">-108</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:109">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:219">failed to sync log</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:220">-109</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:110">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:221">failed to replay log</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:222">-110</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:111">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:223">error http struct</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:224">-111</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:112">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:225">failed to negotiate</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:226">-112</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:113">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:227">failed to change dps metadata</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:228">-113</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:114">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:229">SME is corrupted</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:230">-114</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:115">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:231">application is interrupted</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:232">-115</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:116">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:233">application is disconnected</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:234">-116</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:117">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:235">character encoding errors</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:236">-117</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:118">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:237">get failed msg from the node</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:238">-118</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:119">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:239">buffer array is full</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:240">-119</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:120">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:241">sub context is conflict</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:242">-120</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:121">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:243">coord received EOC message</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:244">-121</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:122">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:245">DPS file size are not the same</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:246">-122</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:123">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:247">dps file not recognise</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:248">-123</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:124">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:249">no resource</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:250">-124</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:125">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:251">invalid lsn</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:252">-125</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:126">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:253">data to pipe is too big</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:254">-126</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:127">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:255">catalog auth failed</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:256">-127</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:128">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:257">node is full sync</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:258">-128</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:129">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:259">catnode failed assign data-node</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:260">-129</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:130">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:261">php driver internal error</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:262">-130</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:131">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:263">failed to send the message</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:264">-131</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:132">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:265">there is no node-group register in catalogue-node</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:266">-132</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:133">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:267">remote-node disconnected</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:268">-133</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:134">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:269">couldn't find the match catalogue-info</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:270">-134</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:135">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:271">update catalog failed</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:272">-135</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:136">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:273">received invalid request which opcode is unknowned</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:274">-136</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:137">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:275">coord couldn't find the group-info in local</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:276">-137</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:138">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:277">dms extent is corrupted</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:278">-138</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:139">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:279">remote cluster manage failed</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:280">-139</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:140">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:281">remote engines have been stopped partially</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:282">-140</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:141">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:283">sdb service is starting</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:284">-141</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:142">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:285">sdb service has already been started</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:286">-142</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:143">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:287">sdb service is restarting</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:288">-143</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:144">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:289">sdb node is already existed</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:290">-144</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:145">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:291">sdb node is not existed</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:292">-145</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:146">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:293">unable to lock</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:294">-146</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:147">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:295">dms state is not compatible with current command</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:296">-147</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:148">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:297">rebuild has already started</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:298">-148</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:149">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:299">rebuild in progress mode</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:300">-149</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:150">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:301">there is no data in the coord-node's cache </stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:302">-150</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:151">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:303">errors occur during the process of evalution</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:304">-151</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:152">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:305">group already exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:306">-152</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:153">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:307">group does not exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:308">-153</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:154">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:309">node does not exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:310">-154</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:155">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:311">failed to start the node</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:312">-155</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:156">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:313">node'configure conflicts</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:314">-156</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:157">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:315">group is empty</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:316">-157</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:158">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:317">The operation is for coord node only</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:318">-158</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:159">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:319">failed to operate on node only</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:320">-159</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:160">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:321">The mutex job already exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:322">-160</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:161">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:323">The specified job does not exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:324">-161</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:162">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:325">The catalog information is corrupted</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:326">-162</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:163">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:327">$shard index can't be dropped</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:328">-163</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:164">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:329">The command can't be run in the node</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:330">-164</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:165">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:331">The command can't be run in the serice plane</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:332">-165</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:166">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:333">The group info not exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:334">-166</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:167">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:335">Group name is conflict</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:336">-167</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:168">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:337">The collection is not sharded</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:338">-168</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:169">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:339">The record does not contains valid sharding key</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:340">-169</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:170">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:341">A task that already exists does not compatible with the new task</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:342">-170</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:171">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:343">The collection does not exists on the specified group</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:344">-171</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:172">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:345">The specified task does not exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:346">-172</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:173">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:347">The record contains more than one sharding key</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:348">-173</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:174">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:349">The mutex task already exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:350">-174</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:175">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:351">The split key is not valid or not in the source group</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:352">-175</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:176">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:353">The split key is on boundary of the source group</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:354">-176</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:177">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:355">The unique index must include all fields in sharding key</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:356">-177</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:178">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:357">Sharding key cannot be updated</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:358">-178</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:179">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:359">There is pending task for the collection space</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:360">-179</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:180">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:361">authority is forbidden</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:362">-180</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:181">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:363">There is no catalog address specified by user</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:364">-181</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:182">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:365">current record has been deleted</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:366">-182</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:183">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:367">search condition cannot match any records</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:368">-183</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:184">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:369">index page is reorged and the pos got different lchild</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:370">-184</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:185">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:371">There are duplicate field name exists in the record</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:372">-185</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:186">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:373">Too many records to be inserted at once</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:374">-186</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:187">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:375">Sort-Merge Join only supports equal predicates</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:376">-187</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:188">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:377">Trace is already started</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:378">-188</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:189">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:379">Trace buffer does not exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:380">-189</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:190">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:381">Trace file is not valid</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:382">-190</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:191">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:383">transaction-lock is incompatible</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:384">-191</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:192">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:385">system is doing rollback</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:386">-192</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:193">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:387">Bad record when doing sdb import </stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:388">-193</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:194">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:389">repeat var name was found</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:390">-194</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:195">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:391">column field is ambiguous</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:392">-195</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:196">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:393">have an error in sql syntax</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:394">-196</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:197">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:395">invalid transactional operation</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:396">-197</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:198">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:397">append to lock-wait-queue</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:398">-198</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:199">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:399">record is deleting</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:400">-199</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:200">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:401">index is dropped or invalid</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:402">-200</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:201">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:403">repeat to create catalog-group</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:404">-201</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:202">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:405">parse json error</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:406">-202</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:203">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:407">log file is out of size</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:408">-203</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:204">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:409">can not remove the only node in the group</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:410">-204</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:205">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:411">need to manually complete the cleanup</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:412">-205</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:206">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:413">can not remove node or group of catalog</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:414">-206</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:207">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:415">group is not exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:416">-207</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:208">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:417">can not remove the group with data in it</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:418">-208</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:209">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:419">end of queue</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:420">-209</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:210">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:421">collection has not sharding index, can not split by percent</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:422">-210</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:211">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:423">the param field not exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:424">-211</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:212">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:425">too many trace break points are specified</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:426">-212</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:213">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:427">prefetchers are all busy</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:428">-213</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:214">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:429">domain not exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:430">-214</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:215">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:431">domain already exist</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:432">-215</stentry>
         </strow>
         <strow class="- topic/strow " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="strow:216">
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:433">group is not in domain</stentry>
            <stentry class="- topic/stentry " xtrf="C:\SequoiaDB\doc\references\exceptionmapping\topics\exceptionmapping_en.dita" xtrc="stentry:434">-216</stentry>
         </strow>
      </simpletable>
   </body>
<related-links class="- topic/related-links "><linkpool class="- topic/linkpool " xtrc="topicref:1" xtrf="C:\SequoiaDB\doc\references\exceptionmapping\exceptionmapping_en.ditamap"><link class="- topic/link " mapclass="- map/topicref " type="topic" xtrc="topicref:1" xtrf="C:\SequoiaDB\doc\references\references_en.ditamap" href="../../topics/references_en.xml" role="parent"><?ditaot usertext?><linktext class="- topic/linktext "><?ditaot gentext?>Reference</linktext></link></linkpool></related-links>
</topic>